"""creating models

Revision ID: 1abdbc0cad1e
Revises: 49b4325dfae5
Create Date: 2024-01-11 07:51:35.416720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abdbc0cad1e'
down_revision = '49b4325dfae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
