"""creating models

Revision ID: 49b4325dfae5
Revises: 8b64f4bf0d2d
Create Date: 2024-01-11 07:45:29.185321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b4325dfae5'
down_revision = '8b64f4bf0d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
