"""creating models

Revision ID: 8b64f4bf0d2d
Revises: 506b0c83d130
Create Date: 2024-01-11 07:41:39.809755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b64f4bf0d2d'
down_revision = '506b0c83d130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('image', sa.String(), nullable=True))
    op.add_column('plants', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('plants', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'created_at')
    op.drop_column('plants', 'price')
    op.drop_column('plants', 'image')
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
